### ISSUE TITLE
Electric field radial distance

### ISSUE THREAD

**Issue by edwardbarak** [edwardbarak/NPQG#4]
**Context:**
At a radial distance of 1 Planck length, i.e., the surface of the Planck sphere, electric field is (e/6)/ (1 squared) which is e/6. 
At a radial distance of 1.5 Planck lengths the field is e/(6*1.5*1.5). 

**Question:**
When you say the "radial distance of 1 Planck length, in other words, the surface of the Planck sphere" are you saying the distance from the center of the sphere to the surface?

**Comment by jmarkmorris** [comment]
Yes, always from the center of the Planck sphere, for both electric field and magnetic field.
